name: dartup_net
author: Ole Martin Gjersvik <olem@olem.org>
description: The main website fro Dartup
homepage: dartup.net
environment:
  sdk: '>=1.8.3 <2.0.0'
dependencies:
  bootstrap: any
  browser: any
  http: any
transformers:
- $dart2js:
    minify: true
- bootstrap:
    url: //maxcdn.bootstrapcdn.com/bootstrap/{{version}}
    version: 3.2.0
